services: 
  calculator:
    image: calculator:v1.0.1
    container_name: exu2-calculadora
    build: 
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8081
        API_BASE: /api
    ports:
      - "80:80"
    networks:
      - exu2-net
  operations:
    image: operations:v1.0.1 
    container_name: exu2-operaciones
    build: 
      context: ./server
    environment:
      SERVER_PORT: 8080
    ports:
      - "8081:8080"
    networks:
      - exu2-net
    depends_on:
      - calculator

networks:
  exu2-net:
    external: false